### ISSUE TITLE
What's the syntax of the match settings?

### ISSUE THREAD

**Issue by Simeonh2021** [sidharth-panwar/logseq-extract-plugin#4]
Thank you for your work! Would you specify the syntax of the match settings? For example, if I want to extract all the text in the block following the word "POINT", how do I write the rule in the setting file?

**Comment by sidharth-panwar** [comment]
Hi,
Thanks for your question and apologies for the delayed response. Here's how it works:
Currently, you can search for a pattern in each block and if the pattern matches then it returns the block. Currently, it doesn't return partial text from the block (as you're expecting) but what it can do, for instance, is return all blocks (with complete text) wherever the text is starting from the word "POINT" or if the word is found inside the block etc.

Hope this helps. In simple terms, it's just searching for the expression you give it and then return the whole block. Currently, it can't return partial text or subset of the block text. It's quite doable so if you're so inclined you can take this code as base and improve on it.
