### ISSUE TITLE
Extract headings as well

### ISSUE THREAD

**Issue by p-rhei** [sidharth-panwar/logseq-extract-plugin#5]
possible to have an option to extract headings as well, and nest highlights for each heading, in order to keep the information structure
sometimes for readability I only highlight certain words, instead of whole sentence, but the context is lost (unless I hover) for the extracted text
therefore I have the keepMeta on, and then highlight whole sentence & emphasize certain words to extract both context & highlighted words (then manually remove highlights on whole sentence after the extraction)

**Comment by sidharth-panwar** [comment]
Yes, it's possible. So, the change that you'll have to make is this:
Currently, the default expr in settings file is this: (==[^=]+==)|(\\*\\*[^\\*]+\\*\\*)
I think if you change it to this: (==[^=]+==)|(\\*\\*[^\\*]+\\*\\*)|(^#) it should work. 

Explanation: Each heading in markdown starts with a # which means that heading 1 is #, heading 2 is ## etc. And what we're saying with this updated syntax is that it should return all blocks which are starting with # (aka heading). This should hopefully solve your problem. I'm closing this issue but if you're still stuck please feel free to reopen it.
