### ISSUE TITLE
About the insertion position of the summary

### ISSUE THREAD

**Issue by skyline-123** [sidharth-panwar/logseq-extract-plugin#7]
Can it support inserting summaries into the head instead of the tail?
Thanks!

**Comment by sidharth-panwar** [comment]
> 

The plugin currently supports extracting summary either at the page level or at the block level. If I understand correctly, what you're asking is whether we can add the summary at the top of the page (for page level extraction) and above the block (when that block is summarized)? 

If yes, then it is doable. I may need to add another configuration which, when changed, performs what you're requesting. For block extract it's easier. Page extracts may be a little more tricky. Usually, the first block can contain either normal text or page properties so I'll have to check that.

**Comment by skyline-123** [comment]
> > 
> 
> The plugin currently supports extracting summary either at the page level or at the block level. If I understand correctly, what you're asking is whether we can add the summary at the top of the page (for page level extraction) and above the block (when that block is summarized)?
> 
> If yes, then it is doable. I may need to add another configuration which, when changed, performs what you're requesting. For block extract it's easier. Page extracts may be a little more tricky. Usually, the first block can contain either normal text or page properties so I'll have to check that.

Yes, you understand me. Because the summary information is more expected to be seen in the header.
Summary information is now displayed at the bottom by default, and may be ignored in future viewing.
I'd love to know your workflow too, if the summary is at the bottom, don't you have similar troubles?

**Comment by sidharth-panwar** [comment]
@skyline-123 This issue is resolved with the latest version v2.0.5. I've added a new setting "keepSummaryAbove" which is set to false by default but if you set it true it achieves the desired behavior.
