### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by kennethaar** [sidharth-panwar/logseq-extract-plugin#8]
I love your plugin for progressive summarisation. But the last few days it won't load.

I even gett this error on Logseq startup. But I don't know if that is related or a separate issue.

![image](https://user-images.githubusercontent.com/5931199/188624412-5e7bcdc4-0dda-4eee-a2c0-e470d2b3dca1.png)

**Comment by L0cast** [comment]
Same issue here with the same message. The issue might be related to the latest Logseq version 0.8.5, as I've never seen the problem before the recent update. The Extract plugin does not run even if I don't click the "Disable now" button. It requires a manual restart through the "Off/On" switch in Plugins.

**Comment by sidharth-panwar** [comment]
Apologies for the really long delay but I believe it should be working now. I think it was something related to logseq rather than the plugin. I tested with 0.8.15 and it's working.
